'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace ShowLoadingPanelFromGrid


	Partial Public Class _Default

		''' <summary>
		''' mainForm control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected mainForm As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ASPxLoadingPanelDemo control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLoadingPanelDemo As Global.DevExpress.Web.ASPxLoadingPanel.ASPxLoadingPanel

		''' <summary>
		''' ASPxGridViewDemo control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxGridViewDemo As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' ASPxCallbackDemo control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxCallbackDemo As Global.DevExpress.Web.ASPxCallback.ASPxCallback
	End Class
End Namespace
